import { DataStore, Predicates } from "aws-amplify";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { Vehicle, Fleet } from "../src/models";
import styles from "../styles/Home.module.css";

export default function Home() {
  const createVehicle = async () => {
    const vehicle = await DataStore.save(
      new Vehicle({
        name: "2006 Jeep Commander",
      })
    );
    console.log(vehicle);
  };

  const createFleet = async () => {
    const fleet = await DataStore.save(
      new Fleet({
        name: "Fleet 1",
        description: "This is Fleet 1",
      })
    );
    console.log(fleet);
  };

  const saveVehicleToFleet = async () => {
    const existingFleet = (await DataStore.query(Fleet))[0];

    const vehicle = (await DataStore.query(Vehicle))[0];

    const updatedVehicle = await DataStore.save(
      Vehicle.copyOf(vehicle, (original) => {
        original.fleet = existingFleet;
      })
    );

    console.log(updatedVehicle);
  };

  const removeVehicleFromFleet = async () => {
    const vehicle = (await DataStore.query(Vehicle))[0];

    const updatedVehicle = await DataStore.save(
      Vehicle.copyOf(vehicle, (original) => {
        original.fleet = null;
      })
    );

    console.log(updatedVehicle);
  };

  const clearVehiclesAndFleets = async () => {
    await DataStore.delete(Vehicle, Predicates.ALL);
    await DataStore.delete(Fleet, Predicates.ALL);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <button onClick={createVehicle}>Create Vehicle</button>

        <button onClick={createFleet}>Create Fleet</button>

        <button onClick={saveVehicleToFleet}>
          Update Vehicle and Save to Fleet
        </button>

        <button onClick={removeVehicleFromFleet}>
          Remove Vehicle from Fleet
        </button>

        <button onClick={clearVehiclesAndFleets}>
          Clear Vehicles and Fleets
        </button>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
