/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://5ucfjmlfa5ahrpys67ht5wwivm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cz23vmsjwjefdjp6apzvgxmrra",
    "aws_cognito_identity_pool_id": "us-east-1:d7ee1bd8-87e6-4304-b381-72a7a9b4ef00",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZWG1qOnCA",
    "aws_user_pools_web_client_id": "78snactv3imp0p6i1do4992ql2",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
